namespace :java do
  desc "initialize folder structure for java files"
  task [:init] do
    unless File.directory?("java/src")
      sh "mkdir -p java/src"
      sh "mkdir -p java/bin"
    end
  end

  desc "create java source files from ruby source"
  task :source => [:init] do
    Dir.glob('lib/*.rb') do |f|
      sh "jrubyc --java -t java/src #{f}"
    end
  end

  desc "compile java source to class files"
  task :compile => [:source] do
    Dir.glob('lib/*.rb') do |f|
      basename = File.basename(f, '.rb')
      sh "javac -cp java/lib/jruby-complete.jar -d java/bin " +
        "java/src/com/trevorwhitney/ioio/domain/#{basename}.java"
    end
  end

  desc "create jar from java class files"
  task :jar => [:compile] do
    sh "jar -cf java/XBeeBimBapDomain.jar -C java/bin com"
  end
end